/*
ProjectEuler.net problem 2
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

4613732
*/

#include <iostream>
#include <vector>

void main()
{
	int max = 4000000;
	std::vector<int>* fibs = new std::vector<int>();
	fibs->push_back(1);
	fibs->push_back(2);
	int index = fibs->size() - 1;
	int evenSum = 0;
	//fibonacci sequence;
	while (fibs->at(index) < max)
	{
		int prev = fibs->at(index - 1);
		fibs->push_back(prev + fibs->at(index));
		index++;
	}

	for each (int fib in *fibs)
	{
		//even check
		if (fib % 2 == 0)
		{
			evenSum += fib;
		}
	}


	std::cout << "sum is " << evenSum << std::endl;
	delete fibs;
	std::cin.get();
}